<a href="https://colab.research.google.com/github/BandanaSingha24/AI-ML-DL-in-Cancer-Genomics/blob/main/01_Python_Foundation%20_for_Bioinformatics/%20Genomics_TCGA_BRCA_Clinical%20data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

 #step 1 : lodind the data

# 1.1 Load the patient clinical data
# comment='#' skips the metadata/header rows starting with a hash symbol
# comment='#' का उपयोग करके हम उन लाइनों को छोड़ रहे हैं जो '#' से शुरू होती हैं
patient_df = pd.read_csv('data_clinical_patient.txt', sep='\t', comment='#')

# 1.2 Load the sample clinical data
sample_df = pd.read_csv('data_clinical_sample.txt', sep='\t', comment='#')

#  Display the first 5 rows of both DataFrames to verify the data
print("--- Patient Data Overview ---")
display(patient_df.head())

print("\n--- Sample Data Overview ---")
display(sample_df.head())

--- Patient Data Overview ---

,PATIENT_ID,LYMPH_NODES_EXAMINED_POSITIVE,NPI,CELLULARITY,CHEMOTHERAPY,COHORT,ER_IHC,HER2_SNP6,HORMONE_THERAPY,INFERRED_MENOPAUSAL_STATE,...,OS_STATUS,CLAUDIN_SUBTYPE,THREEGENE,VITAL_STATUS,LATERALITY,RADIO_THERAPY,HISTOLOGICAL_SUBTYPE,BREAST_SURGERY,RFS_MONTHS,RFS_STATUS
0,MB-0000,10.0,6.044,NaN,NO,1.0,Positve,NEUTRAL,YES,Post,...,0:LIVING,claudin-low,ER-/HER2-,Living,Right,YES,Ductal/NST,MASTECTOMY,140.500000,0:Not Recurred
1,MB-0002,0.0,4.020,High,NO,1.0,Positve,NEUTRAL,YES,Pre,...,0:LIVING,LumA,ER+/HER2- High Prolif,Living,Right,YES,Ductal/NST,BREAST CONSERVING,84.633333,0:Not Recurred
2,MB-0005,1.0,4.030,High,YES,1.0,Positve,NEUTRAL,YES,Pre,...,1:DECEASED,LumB,NaN,Died of Disease,Right,NO,Ductal/NST,MASTECTOMY,153.300000,1:Recurred
3,MB-0006,3.0,4.050,Moderate,YES,1.0,Positve,NEUTRAL,YES,Pre,...,0:LIVING,LumB,NaN,Living,Right,YES,Mixed,MASTECTOMY,164.933333,0:Not Recurred
4,MB-0008,8.0,6.080,High,YES,1.0,Positve,NEUTRAL,YES,Post,...,1:DECEASED,LumB,ER+/HER2- High Prolif,Died of Disease,Right,YES,Mixed,MASTECTOMY,18.800000,1:Recurred

--- Sample Data Overview ---

,PATIENT_ID,SAMPLE_ID,CANCER_TYPE,CANCER_TYPE_DETAILED,ER_STATUS,HER2_STATUS,GRADE,ONCOTREE_CODE,PR_STATUS,SAMPLE_TYPE,TUMOR_SIZE,TUMOR_STAGE,TMB_NONSYNONYMOUS
0,MB-0000,MB-0000,Breast Cancer,Breast Invasive Ductal Carcinoma,Positive,Negative,3.0,IDC,Negative,Primary,22.0,2.0,0.000000
1,MB-0002,MB-0002,Breast Cancer,Breast Invasive Ductal Carcinoma,Positive,Negative,3.0,IDC,Positive,Primary,10.0,1.0,2.615035
2,MB-0005,MB-0005,Breast Cancer,Breast Invasive Ductal Carcinoma,Positive,Negative,2.0,IDC,Positive,Primary,15.0,2.0,2.615035
3,MB-0006,MB-0006,Breast Cancer,Breast Mixed Ductal and Lobular Carcinoma,Positive,Negative,2.0,MDLC,Positive,Primary,25.0,2.0,1.307518
4,MB-0008,MB-0008,Breast Cancer,Breast Mixed Ductal and Lobular Carcinoma,Positive,Negative,3.0,MDLC,Positive,Primary,40.0,2.0,2.615035

In [2]:
# #Step 2 : Merging the clinical datasets
# हिंदी: #Step 2 : क्लीनिकल डेटासेट्स को आपस में मर्ज करना

# 2.1 Merge patient and sample dataframes using 'PATIENT_ID' as the common key
combined_df = pd.merge(patient_df, sample_df, on='PATIENT_ID', how='inner')

# 2.2 Print the shape of the merged dataframe to see total rows and columns
print("--- Merged Data Shape ---")
print(f"Total Rows (Patients/Samples): {combined_df.shape[0]}")
print(f"Total Columns (Features): {combined_df.shape[1]}")

# 2.3 Display the first 5 rows of the combined dataframe to verify the merge
print("\n--- Combined Data Overview ---")
display(combined_df.head())

--- Merged Data Shape ---
Total Rows (Patients/Samples): 2509
Total Columns (Features): 36

--- Combined Data Overview ---

,PATIENT_ID,LYMPH_NODES_EXAMINED_POSITIVE,NPI,CELLULARITY,CHEMOTHERAPY,COHORT,ER_IHC,HER2_SNP6,HORMONE_THERAPY,INFERRED_MENOPAUSAL_STATE,...,CANCER_TYPE_DETAILED,ER_STATUS,HER2_STATUS,GRADE,ONCOTREE_CODE,PR_STATUS,SAMPLE_TYPE,TUMOR_SIZE,TUMOR_STAGE,TMB_NONSYNONYMOUS
0,MB-0000,10.0,6.044,NaN,NO,1.0,Positve,NEUTRAL,YES,Post,...,Breast Invasive Ductal Carcinoma,Positive,Negative,3.0,IDC,Negative,Primary,22.0,2.0,0.000000
1,MB-0002,0.0,4.020,High,NO,1.0,Positve,NEUTRAL,YES,Pre,...,Breast Invasive Ductal Carcinoma,Positive,Negative,3.0,IDC,Positive,Primary,10.0,1.0,2.615035
2,MB-0005,1.0,4.030,High,YES,1.0,Positve,NEUTRAL,YES,Pre,...,Breast Invasive Ductal Carcinoma,Positive,Negative,2.0,IDC,Positive,Primary,15.0,2.0,2.615035
3,MB-0006,3.0,4.050,Moderate,YES,1.0,Positve,NEUTRAL,YES,Pre,...,Breast Mixed Ductal and Lobular Carcinoma,Positive,Negative,2.0,MDLC,Positive,Primary,25.0,2.0,1.307518
4,MB-0008,8.0,6.080,High,YES,1.0,Positve,NEUTRAL,YES,Post,...,Breast Mixed Ductal and Lobular Carcinoma,Positive,Negative,3.0,MDLC,Positive,Primary,40.0,2.0,2.615035

In [3]:
# #Step 3 : Checking for Missing Values

# 3.1 Calculate total missing values for each column
missing_info = combined_df.isnull().sum()

# 3.2 Filter and display only columns that have at least one missing value
# हिंदी: 3.2 केवल उन कॉलम्स को फिल्टर करके देखना जिनमें कम से कम एक मिसिंग वैल्यू है
missing_only = missing_info[missing_info > 0]

print("--- Columns with Missing Values ---")
print(missing_only)

--- Columns with Missing Values ---
LYMPH_NODES_EXAMINED_POSITIVE    266
NPI                              222
CELLULARITY                      592
CHEMOTHERAPY                     529
COHORT                            11
ER_IHC                            83
HER2_SNP6                        529
HORMONE_THERAPY                  529
INFERRED_MENOPAUSAL_STATE        529
INTCLUST                         529
AGE_AT_DIAGNOSIS                  11
OS_MONTHS                        528
OS_STATUS                        528
CLAUDIN_SUBTYPE                  529
THREEGENE                        745
VITAL_STATUS                     529
LATERALITY                       639
RADIO_THERAPY                    529
HISTOLOGICAL_SUBTYPE             135
BREAST_SURGERY                   554
RFS_MONTHS                       121
RFS_STATUS                        21
ER_STATUS                         40
HER2_STATUS                      529
GRADE                            121
PR_STATUS                        529
TUMOR_SIZE                       149
TUMOR_STAGE                      721
dtype: int64

In [4]:
# #Step 4 : Handling Missing Values (Imputation) - Update
# (not important we can apply automatic imputation directly)
# 4.1 Handle Categorical columns by replacing NaN with 'Unknown'
categorical_cols = [
    'CELLULARITY', 'CHEMOTHERAPY', 'ER_IHC', 'HER2_SNP6',
    'HORMONE_THERAPY', 'INFERRED_MENOPAUSAL_STATE', 'INTCLUST',
    'OS_STATUS', 'CLAUDIN_SUBTYPE', 'THREEGENE', 'VITAL_STATUS',
    'LATERALITY', 'RADIO_THERAPY', 'HISTOLOGICAL_SUBTYPE', 'BREAST_SURGERY',
    'RFS_STATUS', 'ER_STATUS', 'HER2_STATUS', 'PR_STATUS'
]
combined_df[categorical_cols] = combined_df[categorical_cols].fillna('Unknown')

# 4.2 Handle Numerical columns by replacing NaN with the Median value
numerical_cols = [
    'LYMPH_NODES_EXAMINED_POSITIVE', 'NPI', 'COHORT',
    'AGE_AT_DIAGNOSIS', 'OS_MONTHS', 'RFS_MONTHS',
    'TUMOR_SIZE', 'TUMOR_STAGE'
]
for col in numerical_cols:
    median_value = combined_df[col].median()
    combined_df[col] = combined_df[col].fillna(median_value)

# 4.3 Re-check if any missing values are left in the entire dataset
remaining_missing = combined_df.isnull().sum().sum()
print("--- Missing Values Verification ---")
print(f"Total remaining missing values in the entire dataframe: {remaining_missing}")

--- Missing Values Verification ---
Total remaining missing values in the entire dataframe: 121

In [5]:
# #Step 4 : Final Automatic Imputation to Fix Remaining 121 Missing Values

# 4.1 Automatically identify categorical and numerical columns
cat_cols = combined_df.select_dtypes(include=['object']).columns
num_cols = combined_df.select_dtypes(include=['int64', 'float64']).columns

# 4.2 Fill Categorical missing values with 'Unknown'
combined_df[cat_cols] = combined_df[cat_cols].fillna('Unknown')

# 4.3 Fill Numerical missing values with Median after forcing numeric conversion
for col in num_cols:
    combined_df[col] = pd.to_numeric(combined_df[col], errors='coerce')
    median_val = combined_df[col].median()
    combined_df[col] = combined_df[col].fillna(median_val)

# 4.4 Final verification check
final_missing = combined_df.isnull().sum().sum()
print("--- Final Missing Values Verification ---")
print(f"Total remaining missing values now: {final_missing}")

--- Final Missing Values Verification ---
Total remaining missing values now: 0

In [6]:
# #Step 5 : Encoding Categorical Receptors to Numbers (0 and 1)

# 5.1 Define a mapping dictionary for Positive and Negative status
# हिंदी: 5.1 Positive और Negative स्टेटस के लिए एक मैपिंग (नंबर) तय करना
status_mapping = {'Positive': 1, 'Negative': 0, 'Unknown': 0}

# 5.2 Apply mapping to the main breast cancer receptor columns
receptor_cols = ['ER_STATUS', 'PR_STATUS', 'HER2_STATUS']

for col in receptor_cols:
    combined_df[col] = combined_df[col].map(status_mapping)

# 5.3 Verify the changes by looking at these specific columns
print("--- Encoded Receptors Overview ---")
display(combined_df[['PATIENT_ID'] + receptor_cols].head())

--- Encoded Receptors Overview ---

  PATIENT_ID  ER_STATUS  PR_STATUS  HER2_STATUS
0    MB-0000          1          0            0
1    MB-0002          1          1            0
2    MB-0005          1          1            0
3    MB-0006          1          1            0
4    MB-0008          1          1            0

In [7]:
from sklearn.model_selection import train_test_split

# #Step 6 : Final Data Preparation for Machine Learning (supervised)

# 6.1 Select the clinical features we want to use for our survival prediction model
# हिंदी: 6.1 उन क्लीनिकल फीचर्स को चुनना जिनका उपयोग हम मॉडल के लिए करना चाहते हैं
features_to_keep = [
    'AGE_AT_DIAGNOSIS', 'TUMOR_SIZE', 'TUMOR_STAGE',
    'ER_STATUS', 'PR_STATUS', 'HER2_STATUS', 'CELLULARITY', 'CHEMOTHERAPY'
]

# 6.2 Define X (Features) and y (Target variable - Survival Status)
X = combined_df[features_to_keep]
y = combined_df['OS_STATUS'].map({'Living': 1, 'Deceased': 0}) # 1 = Living, 0 = Died

# 6.3 Apply One-Hot Encoding to categorical columns like CELLULARITY and CHEMOTHERAPY
X_encoded = pd.get_dummies(X, columns=['CELLULARITY', 'CHEMOTHERAPY'], drop_first=True)

# 6.4 Split the dataset into 80% Training and 20% Testing sets
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42)

# 6.5 Print the final shapes of our datasets
print("--- Data Splitting Completed ---")
print(f"Training Features Shape: {X_train.shape}")
print(f"Testing Features Shape: {X_test.shape}")
print(f"Training Labels (Target) Shape: {y_train.shape}")

--- Data Splitting Completed ---
Training Features Shape: (2007, 11)
Testing Features Shape: (502, 11)
Training Labels (Target) Shape: (2007,)

In [8]:
# #Step 6.5 : Exporting the Cleaned Clinical Dataset

combined_df.to_csv('processed_clinical_data.csv', index=False)
print("--- Success! Your processed dataset has been saved as 'processed_clinical_data.csv' ---")

--- Success! Your processed dataset has been saved as 'processed_clinical_data.csv' ---